export * from './check-data.interface'
export * from './json-request-collect-money.interface'
export * from './response-collect-money.interface';
export * from './notification.interface';
export * from './delete-file-response.interface';
export * from './table.interface';
export * from './check.interface';
export * from './store.interface';
export * from './employee.interface';
export * from './closing.interface';
export * from './error-api.interface';
export * from './start-payment-request.interface';
export * from './end-payment-request.interface';
export * from './novapagos/insert-nova-pago.interface';
export * from './novapagos/detail-nova-pago.interface';